spring.application.name=sales.savvy

spring.datasource.url=jdbc:mysql://localhost:3306/jan_proj
spring.datasource.username=root
spring.datasource.password=Ganesh@2025.
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver
spring.jpa.hibernate.ddl-auto=update

razorpay.key.id=rzp_test_CJ3lV9W7NlBpYe
razorpay.key.secret=oUGcagDJ7wjC0hdZOm1f8VRq
